name: Update Website from README

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc

      - name: Convert README.md to HTML with Styling and Metadata
        run: |
          pandoc README.md \
            -s \
            -o index.html \
            --metadata title="Luke's Profile" \
            --css style.css \
            --template=./.github/templates/custom.html

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Destination Repository
        uses: actions/checkout@v3
        with:
          repository: wulukewu/wulukewu-readme
          token: ${{ secrets.GH_PAGES_DEPLOY }}
          path: deploy

      - name: Copy HTML
        run: |
          cp index.html deploy/

      - name: Commit and Push Changes
        run: |
          cd deploy
          git add index.html
          git commit -m "Update website from README.md"
          git push origin HEAD:main # or HEAD:master
